### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by VarLad** [pepe/janet.kak#1]
janet.kak doesn't work, when installed with plug.kak

**Comment by katesuyu** [comment]
Could you elaborate, possibly specifying specific errors and your version of Kakoune? It worked fine with plug.kak for me, although I do track latest master of Kakoune.

**Comment by VarLad** [comment]
@katesuyu I don't know what the intended behavior is,
It just highlights the syntax
```:buffer *debug*``` shows the following
``` error running hook WinSetOption(filetype=janet)/: parse error: expected a string delimiter after '%' ```

I was on the September 2020 release, but just tried for master build too

**Comment by pepe** [comment]
Oh, I will look in this too. I must say that I neglected this plugin for a while, but now if there is the interest ...

**Comment by clad26** [comment]
@pepe Were you able to reproduce this?

**Comment by pepe** [comment]
Not yet. Hopefully later today.

**Comment by pepe** [comment]
@VarLad indeed, there is this problem, but I am not able to pinpoint the cause. I will continue an investigation.

**Comment by pepe** [comment]
As I finished the last command, it came to my mind what is wrong. I was not escaping the `%` Janet function. It should be fixed in b5d44b1, please can you confirm it?

**Comment by VarLad** [comment]
@pepe Thanks!
One more thing, is linting supported properly yet?
![Screenshot from 2021-02-15 18-46-37](https://user-images.githubusercontent.com/51269425/107951516-7ad23d00-6fbe-11eb-9cd9-913a59b2e965.png)

(Note that this question is unrelated to the current issue)

**Comment by katesuyu** [comment]
> As I finished the last command, it came to my mind what is wrong. I was not escaping the `%` Janet function. It should be fixed in [b5d44b1](https://github.com/pepe/janet.kak/commit/b5d44b1796062b36fa01b06df6c444361d2520eb), please can you confirm it?

I assumed it was something related to escaping; that is a pesky issue I wish Kakoune had a better way to handle. Your fix works for me, I no longer see the error in `*debug*`.

**Comment by pepe** [comment]
@VarLad, oh, it seems git is missing in the URL. I will try to fix it ASAP.

**Comment by pepe** [comment]
The link is fixed as of 491f9ff closing.
